FORMAT: 1A
HOST: http://api.dobigcrossword.com/

# DoBigCrossword

This API is able to handle the functionality of a multiuser crossword creator site

## Registration [/registraion/]

### Register a user [POST]

Use this function if you want to create a new user. Returns
- 200 if the registration was successful 
- 403 if the email address is already in use
- 403 if the password is wrong (too short, too long, too simple, etc.)

+ Request (application/json)

        {
            "email": "johndoe@gmail.com",
            "password": "abc123",
        }


+ Response 200 (application/json)

        {
            "result": "OK",
        }


+ Response 403 (application/json)

        {
            "result": "ERROR",
            "message": "Email address already in use."
        }

+ Response 403 (application/json)

        {
            "result": "ERROR",
            "message": "The password doesn't meet the requirements."
        }

### Check if email address exists [GET]

With this function the client can check whether a given email address is already in use or not. It returns
- 200 if the email address is a valid email address, in this case the is_existing field contains the booleanvalue whether the email address is already used or not
- 400 if the email address is invalid


+ Request (application/json)

        {
            "email": "johndoe@gmail.com",
        }

+ Response 200 (application/json)

        {
            "result": "OK",
            "is_existing": false
        }

+ Response 400 (application/json)

        {
            "result": "ERROR",
            "message": "The email address in invalid."
        }