This is the future place of this file, just the free version of the bloody apiary.io cannot modify the file anywhere else, just in the root directory. 

Later it will be copied from the root ti here. 